using MonoMod.Utils.Cil;
using System.Linq;
using System.Reflection;
using System.Reflection.Emit;

namespace HarmonyLib
{
	internal class LeaveTry
	{
		public override string ToString() => "(autogenerated)";
	}

	internal class Emitter
	{
		internal Emitter(ILGenerator il)
		{
			il.GetProxiedShim<CecilILGenerator>();
		}

		internal static string FormatOperand(object argument)
		{
			if (argument is null)
				return "NULL";
			var type = argument.GetType();

			if (argument is MethodBase method)
				return method.FullDescription();

			if (argument is FieldInfo field)
				return $"{field.FieldType.FullDescription()} {field.DeclaringType.FullDescription()}::{field.Name}";

			if (type == typeof(Label))
				return $"Label{((Label)argument).GetHashCode()}";

			if (type == typeof(Label[]))
				return $"Labels{string.Join(",", [.. ((Label[])argument).Select(l => l.GetHashCode().ToString())])}";

			if (type == typeof(LocalBuilder))
				return $"{((LocalBuilder)argument).LocalIndex} ({((LocalBuilder)argument).LocalType})";

			if (type == typeof(string))
				return argument.ToString().ToLiteral();

			return argument.ToString().Trim();
		}
	}
}
